# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('ORIGINAL', 'ORIGINAL'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('NEGATIVE', 'NEGATIVE'), ('BLACK&WHITE', 'BLACK&WHITE')], default='ORIGINAL', max_length=255)),
            ],
        ),
    ]
