# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjetPython', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='style',
            field=models.CharField(choices=[('ORIGINAL', 'ORIGINAL'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('GREEN', 'GREEN'), ('NEGATIVE', 'NEGATIVE'), ('BLACK&WHITE', 'BLACK&WHITE')], default='ORIGINAL', max_length=255),
        ),
    ]
